version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=atm_project
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - '3306'
  react-app:
    build:
      context: app_frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8080/api
    restart: always
    ports:
      - 3000:80
  phpmyadmin:
    image: 'phpmyadmin'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80